---
- name: Setup gesundheit
  hosts: all
  tags:
    - setup
    - gesundheit
    - monitoring
  become: true
  roles:
    - role: gesundheit
      gesundheit_http_enabled: true
      gesundheit_http_listen_ip: 127.0.0.1
      gesundheit_http_listen_port: 9876
      gesundheit_modules:
        - filename: gotify
          config:
            Handler:
              Module: "gotify"
              Config:
                Url: "{{ vault_gesundheit_gotify.url }}"
                Token: "{{ vault_gesundheit_gotify.token }}"
              Filter:
                - Module: "result-change"
        - filename: handle-remote-ingressmaschine
          config:
            Handler:
              Module: "remote"
              Config:
                Address: "ingressmaschine.merse88b.de:9999"
                # pubkey is vLL+QKR+RKtnbAe+A+YfYOP45hSR+JTqkdK3pl2R1Gk=
                PrivateKey: "{{ vault_gesundheit_node_private_key }}"
                PublicKey: "7n/uq3G/vFojytMenj1cjrfNZIFbjUFtSVPJOJjA+Ro=" # pubkey of ingressmaschine
        - filename: check-heartbeat
          config:
            Check:
              Module: "heartbeat"
              Description: "Send heartbeat"
              Interval: "30s"
        - filename: check-disk-space-root
          config:
            Check:
              Module: "disk-space"
              Description: "Check free space on root partition"
              Interval: "30m"
              Config:
                MountPoint: "/"
                MinAvailable: "1G"
        - filename: check-memory
          config:
            Check:
              Module: "memory"
              Description: "Check available memory"
              Interval: "5m"
              Config:
                MinAvailable: "500M"
        - filename: check-reboot-required
          config:
            Check:
              Module: "file-presence"
              Description: "Check if reboot is required"
              Interval: "1h"
              Config:
                Path: "/run/reboot-required"
                Present: false
        - filename: check-restic-ente-museum-data-health
          config:
            Check:
              Module: "file-mtime"
              Description: "Check restic backup health of ente data"
              Interval: "1h"
              Config:
                Path: "/var/lib/restic/restic-ente-museum-data.stamp"
                MaxAge: "26h"
        - filename: check-restic-ente-database-health
          config:
            Check:
              Module: "file-mtime"
              Description: "Check restic backup health of ente postgres database"
              Interval: "1h"
              Config:
                Path: "/var/lib/restic/restic-ente-database.stamp"
                MaxAge: "26h"
        - filename: check-restic-audiobookshelf-data-health
          config:
            Check:
              Module: "file-mtime"
              Description: "Check restic backup health of audiobookshelf data"
              Interval: "1h"
              Config:
                Path: "/var/lib/restic/restic-audiobookshelf-data.stamp"
                MaxAge: "26h"
