---
- name: Ensure config dir exists
  ansible.builtin.file:
    path: "/etc/containers/systemd/ente"
    state: directory
    mode: "0750"

- name: Add museum config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/containers/systemd/ente/{{ item }}"
    mode: "0640"
  with_items:
    - credentials.yaml
    - museum.yaml
    - podman-ente-museum.container
    - podman-ente-postgres.container
    - ente.postgres-data.volume
    - ente.custom-logs.volume

- name: Reload systemd units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure data dir exists
  ansible.builtin.file:
    path: "/etc/containers/systemd/ente/data"
    state: directory
    mode: "0750"

- name: Restart museum
  ansible.builtin.systemd_service:
    name: podman-ente-museum.service
    state: restarted
