---
- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: present

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
